/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-11-05 22:13:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import edu.bu.cs.cs460.photoshare.Picture;
import edu.bu.cs.cs460.photoshare.PictureDao;
import org.apache.commons.fileupload.FileUploadException;
import java.util.List;
import edu.bu.cs.cs460.photoshare.HasPicturesDao;
import edu.bu.cs.cs460.photoshare.NewUserDao;
import edu.bu.cs.cs460.photoshare.IsFriendsDao;
import edu.bu.cs.cs460.photoshare.NewAlbumDao;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.HasPicturesDao");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.IsFriendsDao");
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.PictureDao");
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.NewAlbumDao");
    _jspx_imports_classes.add("org.apache.commons.fileupload.FileUploadException");
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.NewUserDao");
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.Picture");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      edu.bu.cs.cs460.photoshare.HasPicturesBean hasPicturesBean = null;
      hasPicturesBean = (edu.bu.cs.cs460.photoshare.HasPicturesBean) _jspx_page_context.getAttribute("hasPicturesBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (hasPicturesBean == null){
        hasPicturesBean = new edu.bu.cs.cs460.photoshare.HasPicturesBean();
        _jspx_page_context.setAttribute("hasPicturesBean", hasPicturesBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("hasPicturesBean"), request);
      out.write('\n');
      out.write('\n');
      out.write('\n');
      edu.bu.cs.cs460.photoshare.NewUserBean newUserBean = null;
      newUserBean = (edu.bu.cs.cs460.photoshare.NewUserBean) _jspx_page_context.getAttribute("newUserBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (newUserBean == null){
        newUserBean = new edu.bu.cs.cs460.photoshare.NewUserBean();
        _jspx_page_context.setAttribute("newUserBean", newUserBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("newUserBean"), request);
      out.write('\n');
      out.write('\n');
      out.write('\n');
      edu.bu.cs.cs460.photoshare.IsFriendsBean isFriendsBean = null;
      isFriendsBean = (edu.bu.cs.cs460.photoshare.IsFriendsBean) _jspx_page_context.getAttribute("isFriendsBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (isFriendsBean == null){
        isFriendsBean = new edu.bu.cs.cs460.photoshare.IsFriendsBean();
        _jspx_page_context.setAttribute("isFriendsBean", isFriendsBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("isFriendsBean"), request);
      out.write('\n');
      out.write('\n');
      out.write('\n');
      edu.bu.cs.cs460.photoshare.NewAlbumBean newAlbumBean = null;
      newAlbumBean = (edu.bu.cs.cs460.photoshare.NewAlbumBean) _jspx_page_context.getAttribute("newAlbumBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (newAlbumBean == null){
        newAlbumBean = new edu.bu.cs.cs460.photoshare.NewAlbumBean();
        _jspx_page_context.setAttribute("newAlbumBean", newAlbumBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("newAlbumBean"), request);
      out.write('\n');
      out.write('\n');
      out.write('\n');
      edu.bu.cs.cs460.photoshare.ImageUploadBean imageUploadBean = null;
      imageUploadBean = (edu.bu.cs.cs460.photoshare.ImageUploadBean) _jspx_page_context.getAttribute("imageUploadBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (imageUploadBean == null){
        imageUploadBean = new edu.bu.cs.cs460.photoshare.ImageUploadBean();
        _jspx_page_context.setAttribute("imageUploadBean", imageUploadBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write("\n");
        out.write("    ");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("imageUploadBean"), request);
        out.write('\n');
      }
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head><title>Photo sharing</title></head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<h1>Photo Sharing</h1>\n");
      out.write("\n");
      out.write("Hello <b><code>");
      out.print( request.getUserPrincipal().getName()  );
      out.write("</code></b>, click here to\n");
      out.write("<a href=\"/photoshare/logout.jsp\">log out</a>\n");
      out.write("\n");
      out.write("<h3><a href=\"/photoshare/searchfriend.jsp\">Search and Add Friend</a></h3>\n");
      out.write("\n");
      out.write("<h3><a href=\"newalbum.jsp\">My Albums and Pictures</a></h3>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<h3><a href=\"listallalbums2.jsp\">All Albums and Pictures</a></h3>\n");
      out.write("\n");
      out.write("<h3><a href=\"displayAllPicture.jsp\">Write Comments</a></h3>\n");
      out.write("\n");
      out.write("<h3><a href=\"listallalbums.jsp\">Tag or Like Pictures</a></h3>\n");
      out.write("\n");
      out.write("<h3><a href=\"topusers.jsp\">Top 10 Users</a></h3>\n");
      out.write("\n");
      out.write("<h3><a href=\"searchTag.jsp\">View Photos with a Specific Tag</a></h3>\n");
      out.write("\n");
      out.write("<h3><a href=\"populartag.jsp\">View Most Popular Tag</a></h3>\n");
      out.write("\n");
      out.write("<h3><a href=\"searchmultitags.jsp?id=1\">Search with Conjunctive Tag</a></h3>\n");
      out.write("\n");
      out.write("<h3><a href=\"youmayalsolike.jsp\">You May Also Like</a></h3>\n");
      out.write("\n");
      out.write("<h3><a href=\"searchmultitags.jsp?id=2\">Tag Recommendation</a></h3>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
