/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-11-07 23:18:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.lang.Integer;
import java.lang.util.*;
import java.lang.String;
import edu.bu.cs.cs460.photoshare.NewTagDao;
import edu.bu.cs.cs460.photoshare.CommentUnderPicDao;
import edu.bu.cs.cs460.photoshare.PictureDao;
import edu.bu.cs.cs460.photoshare.HasPicturesDao;
import edu.bu.cs.cs460.photoshare.HasAlbumsDao;
import edu.bu.cs.cs460.photoshare.HasTagsDao;
import edu.bu.cs.cs460.photoshare.NewUserDao;

public final class searchTag_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.lang.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.HasPicturesDao");
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.NewTagDao");
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.HasTagsDao");
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.CommentUnderPicDao");
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.PictureDao");
    _jspx_imports_classes.add("java.lang.String");
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.NewUserDao");
    _jspx_imports_classes.add("java.lang.Integer");
    _jspx_imports_classes.add("edu.bu.cs.cs460.photoshare.HasAlbumsDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      edu.bu.cs.cs460.photoshare.NewTagBean newTagBean = null;
      newTagBean = (edu.bu.cs.cs460.photoshare.NewTagBean) _jspx_page_context.getAttribute("newTagBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (newTagBean == null){
        newTagBean = new edu.bu.cs.cs460.photoshare.NewTagBean();
        _jspx_page_context.setAttribute("newTagBean", newTagBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("newTagBean"), request);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head><title>View Pictures With Specific Tag</title></head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
 // the inpiut tag name is not empty 
  boolean tagFound = false;
	int tid = -1;
	String err = null;
	if (!newTagBean.getName().equals("")) { 
		  
		   String inputTagName = newTagBean.getName();
		   int len = inputTagName.length();
		   boolean containSpace = false;
		   for(int i = 0; i < len; i ++){
		   		if (inputTagName.charAt(i) == ' ') {
					containSpace = true;
				}
			}

		   if(!containSpace) {
		   		NewTagDao newTagDao = new NewTagDao();
		   		HasTagsDao hasTagsDao = new HasTagsDao();
		   
		   		int tempTId = newTagDao.getTagId(inputTagName);
				
				if (tempTId <= 0) {
					err = "Such tag does not exist";
				}else {
					tagFound = true;
					tid = newTagDao.getTagId(inputTagName);
				}
		   }else {
			   err = "Tag name cannot contain space!";
		   }
	} 

      out.write('\n');
      out.write('\n');
 if (err != null) { 
      out.write("\n");
      out.write("<font color=red><b>Error: ");
      out.print( err );
      out.write("</b></font>\n");
 } 
      out.write('\n');
      out.write('\n');
 if (!tagFound) { 
      out.write("\n");
      out.write("\n");
      out.write("<h4>Please enter tag name (single word only)</h4>\n");
      out.write("\n");
      out.write("<form action=\"searchTag.jsp\" method=\"post\">\n");
      out.write("  Tag Name: <input type=\"text\" name=\"tagName\"/><br>\n");
      out.write("  <input type=\"submit\" value=\"Search\"/><br/>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("\n");
 } else { 
		if(request.getUserPrincipal() != null) {

      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<h2>Tag Name Exist</h2>\n");
      out.write("\n");
      out.write("\t\t\t<h3><a href=\"displayMyPicTagName.jsp?tag_Id=");
      out.print(tid);
      out.write("\"> My Pictures</a></h3>\n");
 		}else {  
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<h2>Tag Name Exist</h2>\n");
      out.write("\n");
      out.write("\t\t\t<h3><a href=\"displayPicTagName.jsp?tag_Id=");
      out.print(tid);
      out.write("\"> All Pictures</a></h3>\n");
      out.write("\n");
		}
	}

      out.write("\n");
      out.write("\n");
      out.write("<h4>Return to <a href=\"main.jsp\">Main Page</a></h3>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
